In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from typing import List, Sequence, Union
from pyecharts import options as opts
from pyecharts.commons.utils import JsCode
from pyecharts.charts import Kline, Line, Bar, Grid
from pyecharts.globals import ThemeType

bu = pd.read_csv('data/bu.csv')
jd = pd.read_csv('data/jd.csv')
l = pd.read_csv('data/l.csv')
pp = pd.read_csv('data/pp.csv')
ru = pd.read_csv('data/ru.csv')
v = pd.read_csv('data/v.csv')
bu

            date    open    high     low   close  volume    hold  settle
0     2015-06-26  2948.0  2972.0  2936.0  2960.0   32378   50834  2954.0
1     2015-06-29  2948.0  2970.0  2922.0  2936.0   31124   49566  2952.0
2     2015-06-30  2930.0  2948.0  2804.0  2812.0   52186   48312  2854.0
3     2015-07-01  2832.0  2850.0  2808.0  2826.0   31576   49450  2834.0
4     2015-07-02  2826.0  2830.0  2774.0  2816.0   36706   50466  2802.0
...          ...     ...     ...     ...     ...     ...     ...     ...
2427  2025-06-20  3738.0  3789.0  3723.0  3747.0  253286  284513  3751.0
2428  2025-06-23  3736.0  3804.0  3719.0  3781.0  317501  311332  3769.0
2429  2025-06-24  3762.0  3770.0  3562.0  3580.0  460577  269578  3643.0
2430  2025-06-25  3565.0  3583.0  3537.0  3574.0  282213  251579  3556.0
2431  2025-06-26  3568.0  3584.0  3544.0  3563.0  230736  243021  3562.0

[2432 rows x 8 columns]

In [3]:
#prepare data
def prepare_data(df):
    # set all column name to lower case
    df.columns = df.columns.str.lower()
    # check if it contains date and close price column, if not, report error and exit the function
    if not 'date' in df.columns or not 'close' in df.columns:
        raise ValueError('DataFrame must have at least contain date and close price column')
    # rename the column name
    df = df.rename(columns={
        'date': 'Date',
        'open': 'Open',
        'high': 'High',
        'low': 'Low',
        'close': 'Close',
        'volume': 'Volume'
    })
    # if there is no Open, High, Low, fill it with close price
    if not 'Open' in df.columns:
        df['Open'] = df['Close']
    if not 'High' in df.columns:
        df['High'] = df['Close']
    if not 'Low' in df.columns:
        df['Low'] = df['Close']
    df['Date'] = pd.to_datetime(df['Date'])
    return df.set_index('Date')
test_set = bu.rename(columns={
        'date': 'DaTE',
        'open': 'OpENs',
        'high': 'High',
        'low': 'Low',
        'close': 'ClOsE',
        'volume': 'Volume'
    })
prepare_data(test_set)

             opens    High     Low   Close  Volume    hold  settle    Open
Date
2015-06-26  2948.0  2972.0  2936.0  2960.0   32378   50834  2954.0  2960.0
2015-06-29  2948.0  2970.0  2922.0  2936.0   31124   49566  2952.0  2936.0
2015-06-30  2930.0  2948.0  2804.0  2812.0   52186   48312  2854.0  2812.0
2015-07-01  2832.0  2850.0  2808.0  2826.0   31576   49450  2834.0  2826.0
2015-07-02  2826.0  2830.0  2774.0  2816.0   36706   50466  2802.0  2816.0
...            ...     ...     ...     ...     ...     ...     ...     ...
2025-06-20  3738.0  3789.0  3723.0  3747.0  253286  284513  3751.0  3747.0
2025-06-23  3736.0  3804.0  3719.0  3781.0  317501  311332  3769.0  3781.0
2025-06-24  3762.0  3770.0  3562.0  3580.0  460577  269578  3643.0  3580.0
2025-06-25  3565.0  3583.0  3537.0  3574.0  282213  251579  3556.0  3574.0
2025-06-26  3568.0  3584.0  3544.0  3563.0  230736  243021  3562.0  3563.0

[2432 rows x 8 columns]

In [4]:
new_bu = prepare_data(bu)
new_jd = prepare_data(jd)
new_l = prepare_data(l)
new_pp = prepare_data(pp)
new_ru = prepare_data(ru)
new_v = prepare_data(v)

In [ ]:
def kline_plot(df):
    x_data = [d.strftime("%Y-%m-%d") for d in df.index]
    
    c = (
        Kline(init_opts=opts.InitOpts(bg_color="white", width="1000px", height="600px"))
        .add_xaxis(x_data)
        .add_yaxis("kline",
                   df[['Open','Close','Low','High']].values.tolist(),
            itemstyle_opts=opts.ItemStyleOpts(
                color="#ec0000",
                color0="#00da3c",
                border_color="#000000",
                border_color0="#000000",
                border_width=0.8
            )
        )
        .set_global_opts(
            legend_opts=opts.LegendOpts(is_show=False),
            xaxis_opts=opts.AxisOpts(
                type_="category",
                axisline_opts=opts.AxisLineOpts(is_on_zero=False),
                boundary_gap=True,
            ),
            yaxis_opts=opts.AxisOpts(
                is_scale=True,
                splitarea_opts=opts.SplitAreaOpts(is_show=True)
            ),
            title_opts=opts.TitleOpts(title="K-line Chart"),
            datazoom_opts=[
                opts.DataZoomOpts(
                    type_="inside",
                    orient="horizontal",
                    range_mode="percent",
                ),
                opts.DataZoomOpts(
                    type_="slider",
                    orient="horizontal",
                    range_mode="percent",
                )
            ],
            tooltip_opts=opts.TooltipOpts(trigger="axis")
        )
    )
    return c.render_notebook()

# 使用示例
kline_plot(new_bu)