In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from typing import List, Sequence, Union
from pyecharts import options as opts
from pyecharts.commons.utils import JsCode
from pyecharts.charts import Kline, Line, Bar, Grid
from pyecharts.globals import ThemeType

bu = pd.read_csv('../data/bu.csv')
jd = pd.read_csv('../data/jd.csv')
l = pd.read_csv('../data/l.csv')
pp = pd.read_csv('../data/pp.csv')
ru = pd.read_csv('../data/ru.csv')
v = pd.read_csv('../data/v.csv')
bu

           date    open    high     low   close  volume    hold  settle
0    2021-06-28  3550.0  3578.0  3490.0  3510.0  623026  370726  3530.0
1    2021-06-29  3508.0  3522.0  3462.0  3476.0  444348  348991  3484.0
2    2021-06-30  3498.0  3522.0  3468.0  3494.0  393951  341547  3494.0
3    2021-07-01  3518.0  3526.0  3440.0  3452.0  525057  331998  3482.0
4    2021-07-02  3504.0  3552.0  3474.0  3488.0  475762  332052  3504.0
..          ...     ...     ...     ...     ...     ...     ...     ...
964  2025-06-20  3738.0  3789.0  3723.0  3747.0  253286  284513  3751.0
965  2025-06-23  3736.0  3804.0  3719.0  3781.0  317501  311332  3769.0
966  2025-06-24  3762.0  3770.0  3562.0  3580.0  460577  269578  3643.0
967  2025-06-25  3565.0  3583.0  3537.0  3574.0  282213  251579  3556.0
968  2025-06-26  3568.0  3584.0  3544.0  3563.0  230736  243021  3562.0

[969 rows x 8 columns]

In [3]:
#prepare data
def prepare_data(df):
    # set all column name to lower case
    df.columns = df.columns.str.lower()
    # check if it contains date and close price column, if not, report error and exit the function
    if not 'date' in df.columns or not 'close' in df.columns:
        raise ValueError('DataFrame must have at least contain date and close price column')
    # rename the column name
    df = df.rename(columns={
        'date': 'Date',
        'open': 'Open',
        'high': 'High',
        'low': 'Low',
        'close': 'Close',
        'volume': 'Volume'
    })
    # if there is no Open, High, Low, fill it with close price
    if not 'Open' in df.columns:
        df['Open'] = df['Close']
    if not 'High' in df.columns:
        df['High'] = df['Close']
    if not 'Low' in df.columns:
        df['Low'] = df['Close']
    df['Date'] = pd.to_datetime(df['Date'])
    return df.set_index('Date')
test_set = bu.rename(columns={
        'date': 'DaTE',
        'open': 'OpENs',
        'high': 'High',
        'low': 'Low',
        'close': 'ClOsE',
        'volume': 'Volume'
    })
prepare_data(test_set)

             opens    High     Low   Close  Volume    hold  settle    Open
Date
2021-06-28  3550.0  3578.0  3490.0  3510.0  623026  370726  3530.0  3510.0
2021-06-29  3508.0  3522.0  3462.0  3476.0  444348  348991  3484.0  3476.0
2021-06-30  3498.0  3522.0  3468.0  3494.0  393951  341547  3494.0  3494.0
2021-07-01  3518.0  3526.0  3440.0  3452.0  525057  331998  3482.0  3452.0
2021-07-02  3504.0  3552.0  3474.0  3488.0  475762  332052  3504.0  3488.0
...            ...     ...     ...     ...     ...     ...     ...     ...
2025-06-20  3738.0  3789.0  3723.0  3747.0  253286  284513  3751.0  3747.0
2025-06-23  3736.0  3804.0  3719.0  3781.0  317501  311332  3769.0  3781.0
2025-06-24  3762.0  3770.0  3562.0  3580.0  460577  269578  3643.0  3580.0
2025-06-25  3565.0  3583.0  3537.0  3574.0  282213  251579  3556.0  3574.0
2025-06-26  3568.0  3584.0  3544.0  3563.0  230736  243021  3562.0  3563.0

[969 rows x 8 columns]

In [4]:
new_bu = prepare_data(bu)
new_jd = prepare_data(jd)
new_l = prepare_data(l)
new_pp = prepare_data(pp)
new_ru = prepare_data(ru)
new_v = prepare_data(v)

In [5]:
def kline_plot(df):
    x_data = [d.strftime("%Y-%m-%d") for d in df.index]
    
    c = (
        Kline(init_opts=opts.InitOpts(bg_color="white", width="1000px", height="600px"))
        .add_xaxis(x_data)
        .add_yaxis("kline",
                   df[['Open','Close','Low','High']].values.tolist(),
            itemstyle_opts=opts.ItemStyleOpts(
                color="#ec0000",
                color0="#00da3c",
                border_color="#000000",
                border_color0="#000000",
                border_width=0.8
            )
        )
        .set_global_opts(
            legend_opts=opts.LegendOpts(is_show=False),
            xaxis_opts=opts.AxisOpts(
                type_="category",
                axisline_opts=opts.AxisLineOpts(is_on_zero=False),  # 关闭零轴线对齐
            ),
            yaxis_opts=opts.AxisOpts(
                is_scale=True,
                splitarea_opts=opts.SplitAreaOpts(is_show=True)
            ),
            title_opts=opts.TitleOpts(title="K-line Chart"),
            datazoom_opts=[
                opts.DataZoomOpts(type_="inside", orient="horizontal"),
                opts.DataZoomOpts(type_="slider", orient="horizontal")
            ],
            tooltip_opts=opts.TooltipOpts(trigger="axis")
        )
    )
    return c.render_notebook()

# 使用示例
kline_plot(new_bu)

In [6]:
def kline_plot(df):
    # 准备x轴数据
    x_data = [d.strftime("%Y-%m-%d") for d in df.index]
    
    # 创建K线图
    kline = (
        Kline(init_opts=opts.InitOpts(bg_color="white", width="1000px", height="600px"))
        .add_xaxis(x_data)
        .add_yaxis(
            "kline",
            df[['Open','Close','Low','High']].values.tolist(),
            itemstyle_opts=opts.ItemStyleOpts(
                color="#ec0000",
                color0="#00da3c",
                border_color="#000000",
                border_color0="#000000",
                border_width=0.8
            )
        )
        .set_global_opts(
            legend_opts=opts.LegendOpts(is_show=False),
            xaxis_opts=opts.AxisOpts(
                type_="category",
                axisline_opts=opts.AxisLineOpts(is_on_zero=False),
                boundary_gap=True,
            ),
            yaxis_opts=opts.AxisOpts(
                is_scale=True,
                splitarea_opts=opts.SplitAreaOpts(is_show=True)
            ),
            title_opts=opts.TitleOpts(title="K-line Chart"),
            datazoom_opts=[
                opts.DataZoomOpts(
                    type_="inside",
                    orient="horizontal",
                    range_mode="percent",
                ),
                opts.DataZoomOpts(
                    type_="slider",
                    orient="horizontal",
                    range_mode="percent",
                )
            ],
            tooltip_opts=opts.TooltipOpts(trigger="axis")
        )
    )
    
    # 识别趋势区域并添加标记
    mark_area_items = identify_trend_regions(df, x_data)
    if mark_area_items:
        kline.set_series_opts(
            markarea_opts=opts.MarkAreaOpts(
                data=mark_area_items,
                itemstyle_opts=opts.ItemStyleOpts(opacity=0.3)
            )
        )
    
    return kline.render_notebook()

def identify_trend_regions(df, x_data):
    # 使用开盘价和收盘价的平均值作为价格参考
    prices = df['Close'] * 0.5 + df['Open'] * 0.5
    mark_area_items = []
    
    # 参数设置
    trend_threshold = 0.015  # 趋势识别阈值
    segment_length = 6       # 最小分析段长度
    min_region_length = 10   # 最小区域长度
    big_threshold = 0.055     # 大波动阈值，超过此值不合并
    
    n = len(prices)
    regions = []  # 存储所有识别出的区域 (start_idx, end_idx, trend_type, price_change)

    # 第一步：初步识别所有趋势区域
    i = 0
    while i < n - 1:
        j = i + 1
        while j < n:
            # 使用iloc避免位置索引警告
            price_i = prices.iloc[i]
            price_j = prices.iloc[j]
            price_change = (price_j - price_i) / price_i
            
            if abs(price_change) > trend_threshold:
                regions.append((i, j, "up" if price_change > 0 else "down", price_change))
                break
            if j >= (i + segment_length):  # 无显著趋势，标记为横盘
                regions.append((i, j, "consolidation", price_change))
                break
            j += 1
        
        if j >= n:  # 到达末尾
            break
        i = j

    if not regions:
        return mark_area_items

    # 第二步：合并连续的同类型区域
    merged_regions = []
    current_start, current_end, current_trend, current_change = regions[0]
    
    for i in range(1, len(regions)):
        start_idx, end_idx, trend_type, price_change = regions[i]
        
        if current_trend == trend_type:
            current_end = end_idx
            # 使用iloc重新计算价格变化
            price_start = prices.iloc[current_start]
            price_end = prices.iloc[current_end]
            current_change = (price_end - price_start) / price_start
        else:
            merged_regions.append((current_start, current_end, current_trend, current_change))
            current_start, current_end, current_trend, current_change = start_idx, end_idx, trend_type, price_change
    
    merged_regions.append((current_start, current_end, current_trend, current_change))

    # 第三步：消除小趋势区，但保留大波动区域
    final_regions = []
    i = 0
    n_regions = len(merged_regions)
    
    while i < n_regions:
        start_idx, end_idx, trend_type, price_change = merged_regions[i]
        region_length = end_idx - start_idx + 1
        abs_price_change = abs(price_change)
        
        # 大波动区域直接保留
        if abs_price_change > big_threshold:
            final_regions.append((start_idx, end_idx, trend_type))
            i += 1
            continue
        
        # 区域足够长则保留
        if region_length >= min_region_length:
            final_regions.append((start_idx, end_idx, trend_type))
            i += 1
            continue
        
        # 小区域处理逻辑
        prev_region = final_regions[-1] if final_regions else None
        next_region = merged_regions[i+1] if i+1 < n_regions else None
        
        # 没有相邻区域，直接保留
        if not prev_region and not next_region:
            final_regions.append((start_idx, end_idx, trend_type))
            i += 1
            continue
        
        # 计算两种合并方案的价格变化
        left_merge_change = 0.0
        right_merge_change = 0.0
        
        if prev_region:
            # 左合并：前一区域起点到当前区域终点
            price_prev_start = prices.iloc[prev_region[0]]
            price_current_end = prices.iloc[end_idx]
            left_merge_change = abs((price_current_end - price_prev_start) / price_prev_start)
        
        if next_region:
            # 右合并：当前区域起点到下一区域终点
            price_current_start = prices.iloc[start_idx]
            price_next_end = prices.iloc[next_region[1]]
            right_merge_change = abs((price_next_end - price_current_start) / price_current_start)
        
        # 根据价格变化选择合并方向
        if left_merge_change < right_merge_change and prev_region:
            # 合并到左边区域
            new_start = prev_region[0]
            new_end = end_idx
            new_trend = prev_region[2]
            final_regions.pop()
            final_regions.append((new_start, new_end, new_trend))
            i += 1
        elif next_region:
            # 合并到右边区域（创建新区域）
            new_start = start_idx
            new_end = next_region[1]
            new_trend = next_region[2]
            # 跳过下一个区域（已合并）
            final_regions.append((new_start, new_end, new_trend))
            i += 2  # 跳过当前区域和下一个区域
        else:
            # 没有合适的合并方向，保留当前区域
            final_regions.append((start_idx, end_idx, trend_type))
            i += 1

    # 第四步：生成标记项并设置颜色
    for start_idx, end_idx, trend_type in final_regions:
        if trend_type == "up":
            color = "rgba(165, 214, 167)"
        elif trend_type == "down":
            color = "rgba(239, 154, 154)"
        else:
            color = "rgba(255, 255, 0,0.9)" 
        
        mark_area_items.append([
            {"xAxis": x_data[start_idx], "itemStyle": {"color": color}},
            {"xAxis": x_data[end_idx]}
        ])
    
    return mark_area_items
# 使用示例
kline_plot(new_bu)

In [7]:
kline_plot(new_jd)

In [8]:
kline_plot(new_l)

In [9]:
kline_plot(new_pp)

In [10]:
kline_plot(new_ru)

In [11]:
kline_plot(new_v)